### ISSUE TITLE
refactor dodobot_serial_bridge

### ISSUE THREAD

**Issue by ogunasekara** [Woz4tetra/dodobot-ros#1]
**Code Location**: src/TO_REFACTOR/dodobot_serial_bridge

The node contained in this package should be moved to the db_parsing package and renamed parsing_serial for stylistic consistency.

**Comment by Woz4tetra** [comment]
Can do!

**Comment by ogunasekara** [comment]
@Woz4tetra Here's some more information:

Currently the folder structure is **src/TO_REFACTOR/dodobot_serial_bridge**.

Inside of this folder, we have the include, launch, msg, src, and srv folders with the dodobot_serial_bridge source inside of it. Ideally, what we want is to move the contents of the include, launch, msg, src, and srv folders into **src/db_parsing**. After doing this, **src/db_parsing/CMakeLists.txt** will also need to be updated to show that there is a new node called parsing_serial which is linked to the serial_bridge source code.

Ultimately, we will not have the **src/TO_REFACTOR** folder and instead all of that content will be in **src/db_parsing**. Let me know if you have any questions.

**Comment by Woz4tetra** [comment]
@osguus Can I move the parsing_joystick file to a different folder? dodobot-ros/src/db_joystick for instance? I don't think it makes sense to have this file mixed with the serial bridge

**Comment by ogunasekara** [comment]
@Woz4tetra yeah that works!

**Comment by Woz4tetra** [comment]
How do I push changes for your review? Do I just push to the master branch?

**Comment by ogunasekara** [comment]
You should make a PR and in the request description put the words "closing #1" in it. That will link it to this issue.
